// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxd4cpzRSX4KJEDg2qdKTwRL5C1_Ylb7A',
    appId: '1:866150771085:web:204b62b8a4de8b8b9bf5c4',
    messagingSenderId: '866150771085',
    projectId: 'clientstage-58124',
    authDomain: 'clientstage-58124.firebaseapp.com',
    storageBucket: 'clientstage-58124.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7k6rS74v2gHlDkiE9Rlgj60qtWvuIg7U',
    appId: '1:866150771085:android:9c351e3456405ae29bf5c4',
    messagingSenderId: '866150771085',
    projectId: 'clientstage-58124',
    storageBucket: 'clientstage-58124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALiT2XSXu0o6nLtlbpz-3SpwNRhWuEIQs',
    appId: '1:866150771085:ios:3900b8ed7016de4f9bf5c4',
    messagingSenderId: '866150771085',
    projectId: 'clientstage-58124',
    storageBucket: 'clientstage-58124.appspot.com',
    iosClientId: '866150771085-dt54ip6986avb6ifr0n1rn87lmqk8nao.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientsstage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALiT2XSXu0o6nLtlbpz-3SpwNRhWuEIQs',
    appId: '1:866150771085:ios:3900b8ed7016de4f9bf5c4',
    messagingSenderId: '866150771085',
    projectId: 'clientstage-58124',
    storageBucket: 'clientstage-58124.appspot.com',
    iosClientId: '866150771085-dt54ip6986avb6ifr0n1rn87lmqk8nao.apps.googleusercontent.com',
    iosBundleId: 'com.example.clientsstage',
  );
}
